### PR TITLE
[ci skip] adding user @nnansters

### LINKED ISSUE #8: @conda-forge-admin, please add user @nnansters
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added user @nnansters as instructed in #8.

Merge this PR to add the user. Please do not rerender this PR or change it in any way. It has `[ci skip]` in the commit message to avoid pushing a new build and so the build configuration in the feedstock should not be changed.

Please contact [conda-forge/core](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-contact-core) to have this PR merged, if the maintainer is unresponsive.

Fixes #8

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge/core something really strange is going on here, I'm just trying to add a user?

**Comment by nnansters** [comment]
Seems like there was an issue in the build due to a dependency specification syntax error. Very weird, considering it has been there for months but only recently started popping up, and seemingly somewhat at random too.

Anyway: we've updated our dependency specifications so the build process should run decently now.

**Comment by nnansters** [comment]
@conda-forge-admin, please rerun bot

**Comment by thewchan** [comment]
@conda-forge-admin please rerender

**Comment by nnansters** [comment]
I think we'd better start from the latest version that does build without issues. Should save us some time.

**Comment by thewchan** [comment]
@nnansters  this one is weird, I'm going to try again, usually it's super easy adding a new maintainer

**Comment by nnansters** [comment]
Our source was unbuildable, for a weird reason. New version is fine so not worth wasting too much time on it.

**Pull request closed without merging**
