### PR TITLE
Update to version 0.5.1

### PR DESCRIPTION
**Pull request by nnansters**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nnansters** [comment]
@conda-forge-admin, please rerender

**Comment by nnansters** [comment]
@conda-forge-admin, please rerender

**Comment by nnansters** [comment]
@thewchan, I can't seem to figure out how to add an additional channel to get one of my dependencies. I thought configuring them in the `conda-forge.yaml` would do the trick, but it doesn't seem to do the trick. Anything I'm missing?

**Comment by thewchan** [comment]
@nnansters My understanding is that Conda Forge generally do not allow for dependency not on the Conda Forge or default channels. We'll need to get the dependencies themselves onto Conda Forge first. Also for future reference you don't need to make a PR to bump the version, give it a day or so the bots will automatically detect upstream changes and make a PR here.

**Comment by nnansters** [comment]
Thanks for your reply @thewchan. I've circumvented the problem by swapping out the problematic library for one that is already on conda-forge. I'll wait a bit for the bot to pick up the new version. 

Thanks for shedding some light on this (and the process in general).

**Comment by thewchan** [comment]
Thanks @nnansters, if you are the owner of NannyML I'm more than happy to add you as a maintainer here. Also, we _can_ add the missing dependency onto Conda Forge, for a simple python only package that should be an easy task, so you might not have to switch out the dependency.

**Pull request closed without merging**
